name: integration_test
on: 
  workflow_call: 
    inputs:
      prompt:
        type: string

jobs:
  build_and_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "run integration tests ${{ inputs.prompt }}"